version = "0.1"
license = "GPL"
package = "urban"
depends = "terrame (>= 2.0)"
title = "Urban Dynamics Models"
authors = "Pedro R. Andrade and Washington Franca"
content = "Implementation of Urban Dynamics Models available in the literature using ABM."
